

rule download:
    input:
        "../inputs/in1.txt",
    output:
        "../results/out1.txt",
        "../results/success1.txt"
    shell:
        """
        # ukbmanage recursively pretends to download the data
        # until all the downloads are sucessful
        ukbmanage -i $PWD/{input[0]} -o $PWD/{output[0]} -f 0.7 -s 123

        # at this point all the files should have been downloaded 
        # successfully. Mark success by creating a flag file. 
        touch $PWD/{output[1]}
        """
